App\Entity\User:
    properties:
        username:
            - NotNull: ~
        email:
            - NotBlank: ~
            - Type:
                  type: email
        firstName:
            - NotNull: ~
            - Length:
                  min: 1
                  max: 72
                  minMessage: 'Your text of first name must be at least {{ limit }} characters long'
                  maxMessage: 'Your text of first name  cannot be longer than {{ limit }} characters'
        lastName:
            - NotNull: ~
            - Length:
                  min: 1
                  max: 72
                  minMessage: 'Your text of last name must be at least {{ limit }} characters long'
                  maxMessage: 'Your text of last name  cannot be longer than {{ limit }} characters'
